/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgentControlCenterRouteImport } from './routes/agent-control-center'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as LoginRouteImport } from './routes/login'
import { Route as QueueRouteImport } from './routes/queue'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as StrategyRouteImport } from './routes/strategy'
import { Route as TelemetryRouteImport } from './routes/telemetry'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentControlCenterRoute = AgentControlCenterRouteImport.update({
  id: '/agent-control-center',
  path: '/agent-control-center',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const QueueRoute = QueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const StrategyRoute = StrategyRouteImport.update({
  id: '/strategy',
  path: '/strategy',
  getParentRoute: () => rootRouteImport,
} as any)
const TelemetryRoute = TelemetryRouteImport.update({
  id: '/telemetry',
  path: '/telemetry',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agent-control-center': typeof AgentControlCenterRoute
  '/agents': typeof AgentsRoute
  '/analytics': typeof AnalyticsRoute
  '/login': typeof LoginRoute
  '/queue': typeof QueueRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/strategy': typeof StrategyRoute
  '/telemetry': typeof TelemetryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agent-control-center': typeof AgentControlCenterRoute
  '/agents': typeof AgentsRoute
  '/analytics': typeof AnalyticsRoute
  '/login': typeof LoginRoute
  '/queue': typeof QueueRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/strategy': typeof StrategyRoute
  '/telemetry': typeof TelemetryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agent-control-center': typeof AgentControlCenterRoute
  '/agents': typeof AgentsRoute
  '/analytics': typeof AnalyticsRoute
  '/login': typeof LoginRoute
  '/queue': typeof QueueRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/strategy': typeof StrategyRoute
  '/telemetry': typeof TelemetryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agent-control-center'
    | '/agents'
    | '/analytics'
    | '/login'
    | '/queue'
    | '/settings'
    | '/signup'
    | '/strategy'
    | '/telemetry'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agent-control-center'
    | '/agents'
    | '/analytics'
    | '/login'
    | '/queue'
    | '/settings'
    | '/signup'
    | '/strategy'
    | '/telemetry'
  id:
    | '__root__'
    | '/'
    | '/agent-control-center'
    | '/agents'
    | '/analytics'
    | '/login'
    | '/queue'
    | '/settings'
    | '/signup'
    | '/strategy'
    | '/telemetry'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentControlCenterRoute: typeof AgentControlCenterRoute
  AgentsRoute: typeof AgentsRoute
  AnalyticsRoute: typeof AnalyticsRoute
  LoginRoute: typeof LoginRoute
  QueueRoute: typeof QueueRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  StrategyRoute: typeof StrategyRoute
  TelemetryRoute: typeof TelemetryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent-control-center': {
      id: '/agent-control-center'
      path: '/agent-control-center'
      fullPath: '/agent-control-center'
      preLoaderRoute: typeof AgentControlCenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/queue': {
      id: '/queue'
      path: '/queue'
      fullPath: '/queue'
      preLoaderRoute: typeof QueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/strategy': {
      id: '/strategy'
      path: '/strategy'
      fullPath: '/strategy'
      preLoaderRoute: typeof StrategyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/telemetry': {
      id: '/telemetry'
      path: '/telemetry'
      fullPath: '/telemetry'
      preLoaderRoute: typeof TelemetryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentControlCenterRoute: AgentControlCenterRoute,
  AgentsRoute: AgentsRoute,
  AnalyticsRoute: AnalyticsRoute,
  LoginRoute: LoginRoute,
  QueueRoute: QueueRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  StrategyRoute: StrategyRoute,
  TelemetryRoute: TelemetryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
